### ISSUE TITLE
Build error using Xcode 16

### ISSUE THREAD

**Issue by bastianmorath** [Esri/arcgis-maps-sdk-swift#22] opened 2024-09-16 08:23 UTC
Hi,

Our app does not build anymore using Xcode 16 with the following error:

<img width="872" alt="image" src="https://github.com/user-attachments/assets/a96acdff-c370-4e46-a529-54cf6be4fc9e">

Is there anything we can do to fix this?

**Comment by nixta** [comment] 2024-09-16 16:04
Unfortunately right now you have to use Xcode 15 to work with ArcGIS Maps SDK for Swift 200.5. We apologize for the situation and have been working closely with Apple to resolve it over the last week since Xcode 16 RC was released.

Esri will publish guidance shortly. I'll update this issue with a link when that becomes available.

**Comment by nixta** [comment] 2024-09-17 03:49
[Here’s the blog post](https://community.esri.com/t5/arcgis-maps-sdks-native-blog/xcode-16-compatibility-issue-with-arcgis-maps-sdk/ba-p/1539094) in Esri community about the issue.

**Comment by nixta** [comment] 2024-09-23 17:33
This can be closed. We released 200.5.1 last week which should resolve the issue and have had no feedback so far that it does not.

We have the following external resources:
- [Technical Support Article](https://support.esri.com/en-us/knowledge-base/000033636) (this should be the primary resource, now that things have settled down).
- [Esri Community blog post](https://community.esri.com/t5/arcgis-maps-sdks-native-blog/resolved-xcode-16-compatibility-issue-with-arcgis/ba-p/1539094).
- [200.5.1 release notes](https://developers.arcgis.com/swift/release-notes/release-notes-for-200-5/#20051) (which including instructions for removing any Swift Concurrency related build warnings/errors as a result of the changes we had to make for 200.5.1.

Turns out the issue was caused by a bug in Xcode 15.4, which was fixed in Xcode 16. Here is the definitive reply from Apple on the DTS ticket:

> The compiler shipped with 15.4 had a bug that didn't erase any Sendable type to Any when qualified generic types were used in parameter and result positions. This meant that, even though a declaration might have had @preconcurrency, dynamic and static libraries would get a symbol referencing any Sendable. Building against such a dylib with Xcode 6.0 unfortunately causes issues because the 6.0 compiler fixed this bug and now enforces removal of any Sendable. That is why you see [Swift.String: Any] in your error message.
>
> To continue using a dylib built with Xcode 15.4 with newer Xcodes, you should remove @preconcurrency from any declarations that reference any Sendable. Rebuilding the dylib with a newer compiler would also solve the issue since the symbols would be corrected; however, to use this library with older Xcodes, you would need to introduce an additional overload where all instances of 'Any' referenced by a Sendable are manually replaced because the older compiler won't erase them.
>
> Users who built their frameworks in versions prior to Xcode 15.4 "should" not encounter issues when incorporating those frameworks into Xcode 16, as the bug causing problems was introduced in Xcode 15.4.

Note that given their root cause description in the first paragraph above, and our own testing, we think that their advice in the second paragraph to "remove @preconcurrency from any declarations that reference any Sendable" is excessive and our change should suffice, but please continue to monitor Esri Community posts for evidence that 200.5.1 did not fully fix the issue.

**Closed by nixta** 2024-09-23 17:33 UTC
